import { PrimeReactProvider } from 'primereact/api';
import { Inter } from 'next/font/google';
import './globals.css';
import 'primereact/resources/themes/lara-light-cyan/theme.css';
import 'primeicons/primeicons.css';
import "primeflex/primeflex.css";
        

// Initialize the Inter font
const inter = Inter({ subsets: ['latin'] });

// Metadata object
export const metadata = {
  title: 'Login - Homecleaningsg',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PrimeReactProvider>
          {children}
        </PrimeReactProvider>
      </body>
    </html>
  );
}
